global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'zkrandom-monitor'
    environment: '${ENVIRONMENT:-development}'

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # ZKRandom API metrics
  - job_name: 'zkrandom-api'
    static_configs:
      - targets: ['zkrandom-api:3000']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s
    scheme: http

  # Node.js application metrics
  - job_name: 'zkrandom-app-metrics'
    static_configs:
      - targets: ['zkrandom-api:9090']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # MongoDB metrics (if mongodb_exporter is available)
  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb-exporter:9216']
    scrape_interval: 30s

  # Redis metrics (if redis_exporter is available)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

  # System metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # Docker metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Blockchain RPC endpoints health
  - job_name: 'blockchain-rpc'
    static_configs:
      - targets:
        - 'mainnet.base.org:443'
        - 'sepolia.base.org:443'
    metrics_path: '/health'
    scheme: https
    scrape_interval: 60s
    scrape_timeout: 30s

  # zkVerify service health
  - job_name: 'zkverify-service'
    static_configs:
      - targets: ['relayer.zkverify.io:443']
    metrics_path: '/health'
    scheme: https
    scrape_interval: 60s
    scrape_timeout: 30s

# Remote write configuration (optional - for external monitoring)
# remote_write:
#   - url: "https://prometheus-remote-write-endpoint"
#     basic_auth:
#       username: "${REMOTE_WRITE_USERNAME}"
#       password: "${REMOTE_WRITE_PASSWORD}"

# Storage configuration
storage:
  tsdb:
    path: /prometheus
    retention.time: 30d
    retention.size: 10GB